import Head from "next/head";
import style from "../styles/Home.module.css";
import getWeather from "../api/getWeather";

export default function Home() {
  const data = getWeather();
  console.log(data)

  return (
    <>
      <Head>
        <title>Abtion 2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${style.main} `}>
        <h2>temperature</h2>
        {data.main ? (
          <section>
            <h2>{data.main.temp}</h2>
            <p>
              {data.weather[0].description}
            </p>
          </section>
        ) : (
          <p>Loading...</p>
        )}
      </main>
    </>
  );
}
