import Head from "next/head";
import { useState } from "react";
import getWeather from "../api/getWeather";
import getForecast from "@/api/getForecast";
import { Header } from "../components/Header";
import { Today } from "../components/Today";
import { NextWeek } from "../components/NextWeek";

export default function Home() {
  const active = 'text-black dark:text-white';
  const inactive = 'text-neutral-400';

  const [lastWeek, setLastWeek] = useState({style: inactive, clicked: false});
  const [today, setToday] = useState({style: active, clicked: true});
  const [nextWeek, setNextWeek] = useState({style: inactive, clicked: false});


  const clickHandler = (e) => {
    if(e.target.innerText === 'today') {
      setNextWeek({style: inactive, clicked: false});
      setLastWeek({style: inactive, clicked: false});
      setToday({style: active, clicked: true});
    } else if (e.target.innerText === 'last week') {
      setToday({style: inactive, clicked: false});
      setNextWeek({style: inactive, clicked: false});
      setLastWeek({style: active, clicked: true});
    } else if (e.target.innerText === 'next week') {
      setNextWeek({style: active, clicked: true});
      setLastWeek({style: inactive, clicked: false});
      setToday({style: inactive, clicked: false});
    }
  }

  const data = getWeather();
  const forecast = getForecast();

  return (
    <div className="h-screen flex flex-col">
      <Head>
        <title>Abtion 2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {data.main ? (
        <>
          <Header data={data} />
          <main className='py-8 px-10 bg-[#F5C023] dark:bg-[#0F101C] h-screen'>
            <nav className="mb-[50px]">
              <ul className="flex justify-between text-[20px] cursor-pointer">
                <li className={`${lastWeek.style}`} onClick={clickHandler}>last week</li>
                <li className={`${today.style}`} onClick={clickHandler}>today</li>
                <li className={`${nextWeek.style}`} onClick={clickHandler}>next week</li>
              </ul>
            </nav>
            <section>
              {today.clicked ? <Today data={data} /> : null}
              {lastWeek.clicked ? <p>Last week</p> : null}
              {nextWeek.clicked ? <NextWeek forecast={forecast} /> : null}
            </section>
          </main>
        </>
      ) : (
        <p>Loading...</p>
      )}
    </div>
  );
}
